fix: allow disabling Kubo 'localhost' testing
ipfs/gateway-conformance pull request #210
Opened 2024-05-23 17:12 UTC by SgtPooki

Fixes https://github.com/ipfs/gateway-conformance/issues/185

2024-05-23 17:34 UTC, lidel requested changes
I am afraid we can't add Kubo-specific hacks like this to implementation-agnostic test cases.

Let's park this until we have https://github.com/ipfs/gateway-conformance/issues/185#issuecomment-2127705680 sorted out.

2024-05-23 17:35 UTC, SgtPooki commented
FYI I just tested this against https://github.com/ipfs/helia-verified-fetch/pull/85/files#diff-175730b97b315afceee1b708f9bd876588ef883662dc52e139a7961ac7804c56R100 and it doesn't seem to fix the problem

```
  @helia/verified-fetch - gateway conformance
    conformance testing
2024-05-23T17:34:33.543Z conformance-tests:before Using custom gateway-conformance binary at /Users/sgtpooki/code/work/protocol.ai/ipfs/gateway-conformance/gateway-conformance
2024-05-23T17:34:34.609Z basic-server:request:trace set fixingGwcAnnoyance to true for /ipfs/bafkreicysg23kiwv34eg2d7qweipxwosdo2py4ldv42nbauguluen5v6am/, with host header localhost
2024-05-23T17:34:34.614Z basic-server:request:trace set fixingGwcAnnoyance to true for http://localhost/ipfs/bafkreicysg23kiwv34eg2d7qweipxwosdo2py4ldv42nbauguluen5v6am/, with host header localhost
2024-05-23T17:34:34.617Z basic-server:request:trace set fixingGwcAnnoyance to true for /ipfs/bafybeig675grnxcmshiuzdaz2xalm6ef4thxxds6o6ypakpghm5kghpc34/Portugal%252C+Espa%C3%B1a=Peninsula%20Ib%C3%A9rica.txt, with host header localhost
2024-05-23T17:34:34.622Z basic-server:request:trace set fixingGwcAnnoyance to true for http://localhost/ipfs/bafybeig675grnxcmshiuzdaz2xalm6ef4thxxds6o6ypakpghm5kghpc34/Portugal%252C+Espa%C3%B1a=Peninsula%20Ib%C3%A9rica.txt, with host header localhost
2024-05-23T17:34:34.647Z basic-server:request:trace set fixingGwcAnnoyance to true for /ipfs/bafybeiht6dtwk3les7vqm6ibpvz6qpohidvlshsfyr7l5mpysdw2vmbbhe/, with host header localhost
2024-05-23T17:34:34.652Z basic-server:request:trace set fixingGwcAnnoyance to true for http://localhost/ipfs/bafybeiht6dtwk3les7vqm6ibpvz6qpohidvlshsfyr7l5mpysdw2vmbbhe/, with host header localhost
2024-05-23T17:34:34.655Z basic-server:request:trace set fixingGwcAnnoyance to true for /ipfs/QmZULkCELmmk5XNfCgTnCyFgAVxBRBXyDHGGMVoLFLiXEN/, with host header localhost
2024-05-23T17:34:34.661Z basic-server:request:trace set fixingGwcAnnoyance to true for http://localhost/ipfs/QmZULkCELmmk5XNfCgTnCyFgAVxBRBXyDHGGMVoLFLiXEN/, with host header localhost
2024-05-23T17:34:34.703Z basic-server:request:trace set fixingGwcAnnoyance to true for /ipfs/bafkreicysg23kiwv34eg2d7qweipxwosdo2py4ldv42nbauguluen5v6am/, with host header localhost
2024-05-23T17:34:34.708Z basic-server:request:trace set fixingGwcAnnoyance to true for http://localhost/ipfs/bafkreicysg23kiwv34eg2d7qweipxwosdo2py4ldv42nbauguluen5v6am/, with host header localhost
2024-05-23T17:34:34.710Z basic-server:request:trace set fixingGwcAnnoyance to true for /ipfs/QmInvalidCID, with host header localhost
2024-05-23T17:34:34.713Z basic-server:request:trace set fixingGwcAnnoyance to true for http://localhost/ipfs/QmInvalidCID, with host header localhost
2024-05-23T17:34:34.713Z basic-server:request:trace set fixingGwcAnnoyance to true for /ipfs/QmZULkCELmmk5XNfCgTnCyFgAVxBRBXyDHGGMVoLFLiXEN/, with host header localhost
2024-05-23T17:34:34.718Z basic-server:request:trace set fixingGwcAnnoyance to true for http://localhost/ipfs/QmZULkCELmmk5XNfCgTnCyFgAVxBRBXyDHGGMVoLFLiXEN/, with host header localhost
2024-05-23T17:34:34.721Z basic-server:request:trace set fixingGwcAnnoyance to true for /ipfs/bafkreicysg23kiwv34eg2d7qweipxwosdo2py4ldv42nbauguluen5v6am/, with host header localhost
2024-05-23T17:34:34.726Z basic-server:request:trace set fixingGwcAnnoyance to true for http://localhost/ipfs/bafkreicysg23kiwv34eg2d7qweipxwosdo2py4ldv42nbauguluen5v6am/, with host header localhost
2024-05-23T17:34:34.729Z basic-server:request:trace set fixingGwcAnnoyance to true for /ipfs/?uri=ipfs%3A%2F%2FQmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco%2Fwiki%2FDiego_Maradona.html, with host header localhost
2024-05-23T17:34:34.731Z basic-server:request:trace set fixingGwcAnnoyance to true for http://localhost/ipfs/?uri=ipfs%3A%2F%2FQmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco%2Fwiki%2FDiego_Maradona.html, with host header localhost
2024-05-23T17:34:34.734Z basic-server:request:trace set fixingGwcAnnoyance to true for /ipfs/bafkrgqhhyivzstcz3hhswshfjgy6ertgmnqeleynhwt4dlfsthi4hn7zgh4uvlsb5xncykzapi3ocd4lzogukir6ksdy6wzrnz6ohnv4aglcs, with host header localhost
2024-05-23T17:34:34.738Z basic-server:request:trace set fixingGwcAnnoyance to true for http://localhost/ipfs/bafkrgqhhyivzstcz3hhswshfjgy6ertgmnqeleynhwt4dlfsthi4hn7zgh4uvlsb5xncykzapi3ocd4lzogukir6ksdy6wzrnz6ohnv4aglcs, with host header localhost
      ✔ TestGatewaySubdomains has a success rate of at least 41.35% (1273ms)
2024-05-23T17:34:34.820Z conformance-tests:after Not removing custom gateway-conformance binary at /Users/sgtpooki/code/work/protocol.ai/ipfs/gateway-conformance/gateway-conformance
```

2024-05-23 17:38 UTC, SgtPooki commented
> I am afraid we can't add Kubo-specific hacks like this to implementation-agnostic test cases.

I'm confused.. This PR is attempting to allow an escape hatch for dependence on Kubo specific behavior.

2024-05-23 22:06 UTC, lidel commented
Sorry, what I meant is that we should fix conformance tests and not introduce configuration with "kubo" in name to work around have dependency on Kubo specific behavior.

2024-06-07 23:38 UTC, lidel commented
Reported. A picture for future reference, in case the exploit and the comment above gets deleted ;-)
![2024-06-08_01-32](https://github.com/ipfs/gateway-conformance/assets/157609/900e5bf1-6d56-450f-b6a2-d846f6507c5c)

2024-06-10 18:45 UTC, lidel commented
Hardcoded matrix that run subdomain tests against `localhost` is removed in https://github.com/ipfs/gateway-conformance/pull/211, which will ship in v6, so closing this one.

Once that PR is merged, tests will be run against `--subdomain-url`, and there will be no implicit tests against host that was not explicitly passed via this parameter.

2024-06-10 18:45 UTC, closed without merging